/* Static design prototype. No network requests, real auth, or telemetry. */
'use strict';
const design = document.body.dataset.design;
const arcade = design === 'arcade';
const samplePeople = [
  {id:'penny',name:'Penny Lane',handle:'penny_l_demo',initials:'PL',color:'#edd39a',free:128400000,month:18400000,local:18200000,localMonth:3200000,title:'The reigning Top Cheapo',bio:'Shipping side projects. Hoarding the change.',streak:21},
  {id:'cache',name:'Cache Me Outside',handle:'cache_me_demo',initials:'CM',color:'#b7c9f0',free:96700000,month:21600000,local:32100000,localMonth:7800000,title:'Certified Penny Pincher',bio:'Will cache absolutely anything except feelings.',streak:17},
  {id:'frugal',name:'Frugal Fran',handle:'frugalfran_demo',initials:'FF',color:'#dfb4e6',free:81200000,month:12300000,local:61400000,localMonth:12400000,title:'Budget Royalty',bio:'The best things in code are free. Sometimes.',streak:14},
  {id:'bill',name:'No Bill Bill',handle:'no_bill_demo',initials:'BB',color:'#c6dcb6',free:64800000,month:14700000,local:8600000,localMonth:1200000,title:'The Frugal Engineer',bio:'Less billing. More building.',streak:12},
  {id:'token',name:'Token Gesture',handle:'token_demo',initials:'TG',color:'#f5b6a5',free:51200000,month:8900000,local:22500000,localMonth:6100000,title:'Certified Cheapo',bio:'Small models, surprisingly large to-do list.',streak:9},
  {id:'byte',name:'Byte Sized Budget',handle:'byte_size_demo',initials:'BY',color:'#c1dadb',free:38600000,month:11400000,local:4800000,localMonth:700000,title:'Resourceful Rascal',bio:'Making every request count.',streak:8},
  {id:'loose',name:'Loose Change',handle:'loosecoin_demo',initials:'LC',color:'#e5c6ad',free:29400000,month:6400000,local:15700000,localMonth:2900000,title:'Coin Collector',bio:'Currently accepting compliments, not invoices.',streak:6},
  {id:'ctrl',name:'Ctrl Alt Defeat Bills',handle:'ctrl_no_bill',initials:'CA',color:'#c8c0e5',free:21700000,month:4700000,local:9900000,localMonth:1600000,title:'Rising Cheapo',bio:'A very economical origin story.',streak:4}
];
const demoPerson = {id:'you',name:'Guest Cheapo',handle:'guest_cheapo',initials:'YOU',color:'#a9dfb9',free:41600000,month:9700000,local:12000000,localMonth:2400000,title:'Freshly Minted Cheapo',bio:'Here to build things and keep the bill small.',streak:3};
let joined = false;
try { joined = localStorage.getItem('cheapos-leaderboard-demo-opt-in') === 'yes'; } catch (_) { /* private browsing still works */ }
let state = {period:'lifetime',category:'free',query:''};
const app = document.getElementById('app');
const modal = document.getElementById('modal');
let toastTimer;
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format = n => n >= 1e9 ? (n/1e9).toFixed(2)+'B' : (n/1e6).toFixed(1)+'M';
const allPeople = () => joined ? [...samplePeople,demoPerson] : [...samplePeople];
const field = () => state.category === 'free' ? (state.period === 'month' ? 'month' : 'free') : (state.period === 'month' ? 'localMonth' : 'local');
const ranked = () => allPeople().sort((a,b) => b[field()]-a[field()] || a.id.localeCompare(b.id));
const sum = key => allPeople().reduce((n,p)=>n+p[key],0);
const avatar = p => `<span class="avatar" style="--avatar:${p.color}" aria-hidden="true">${p.initials}</span>`;
const trophy = `<svg class="trophy" viewBox="0 0 160 164" aria-hidden="true"><path d="M44 19h72v37c0 24-15 43-36 43S44 80 44 56V19Z" fill="currentColor"/><path d="M43 29H21v20c0 20 12 30 31 30M117 29h22v20c0 20-12 30-31 30" fill="none" stroke="currentColor" stroke-width="10"/><path d="M72 95h16v29h21v15H51v-15h21Z" fill="currentColor"/><path d="m80 34 6 13 14 2-10 10 2 14-12-7-12 7 2-14-10-10 14-2Z" fill="var(--trophy-star,#f8f5ed)"/><path d="M45 147h70" stroke="currentColor" stroke-width="6"/></svg>`;
const arrow = '<span aria-hidden="true">↗</span>';
function notify(message) { const el=document.getElementById('toast'); el.textContent=message; el.classList.add('visible'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('visible'),3600); }
function setJoined(value) { joined=value; try { localStorage.setItem('cheapos-leaderboard-demo-opt-in', value?'yes':'no'); } catch (_) {} }
function shell() {
  app.innerHTML = `<div class="demo-bar"><a href="index.html">← Design studio</a><span><i></i>Interactive concept · fictional stats · nothing uploaded</span><a href="${arcade?'club':'arcade'}.html">${arcade?'Try the Club':'Try the Arcade'} ${arrow}</a></div>
  <header class="site-header"><a class="brand" href="${design}.html"><img src="brand-icon.svg" width="38" height="38" alt="">cheapoS <span>${arcade?'TOKEN ARCADE':'THE CHEAPSKATE CLUB'}</span></a><nav aria-label="Main"><a class="active" href="#leaderboard">Leaderboard</a><button class="text-button" data-action="how">How it works</button><button class="button primary" data-action="join">${joined?'Your membership':arcade?'Join the game':'Join the club'} ${arrow}</button></nav></header>
  <main class="page"><div id="hero"></div><div id="community-stats"></div><div class="board-layout"><section class="leaderboard-section" id="leaderboard" aria-labelledby="board-title"><div class="board-heading"><div><div class="eyebrow">${arcade?'THE HIGH-SCORE TABLE':'GOOD COMPANY. GREAT ECONOMY.'}</div><h2 id="board-title">${arcade?'The leaderboard':'Proudly cheap.'}</h2></div><div class="segmented" role="group" aria-label="Leaderboard time period"><button data-period="lifetime" aria-pressed="true">All time</button><button data-period="month" aria-pressed="false">This month</button></div></div><div class="board-toolbar"><div class="category-tabs" role="group" aria-label="Token category"><button data-category="free" aria-pressed="true">Free API tokens</button><button data-category="local" aria-pressed="false">Local tokens</button></div><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Find a fellow cheapo" aria-label="Search participants" autocomplete="off"></label></div><div id="ranking" aria-live="polite" aria-atomic="false"></div><p class="board-footnote" id="board-note"></p></section><aside id="side-panel"></aside></div><section class="bottom-banner"><span class="banner-star" aria-hidden="true">✳</span><div><h2>${arcade?'Build something. Keep the change.':'Being cheap looks good on you.'}</h2><p>Your next side project might just earn you a spot on the board.</p></div><button class="button" data-action="join">${joined?'Your membership':'Count me in'} ${arrow}</button></section></main><footer class="site-footer"><a class="brand" href="index.html"><img src="brand-icon.svg" alt="" width="25" height="25">cheapoS</a><span>Make expensive compute the exception.</span><button class="text-button" data-action="privacy">Your data, your call</button></footer>`;
  renderHero(); renderStats(); renderBoard(); renderSide();
  document.getElementById('search').value=state.query;
  document.getElementById('search').addEventListener('input', e=>{state.query=e.target.value;renderBoard();});
}
function renderHero() {
  const leaders=[...allPeople()].sort((a,b)=>b.free-a.free).slice(0,3);
  if (!arcade) {
    const p=leaders[0];
    document.getElementById('hero').innerHTML=`<section class="hero club-hero"><div class="hero-copy"><div class="eyebrow"><span class="little-spark">✳</span> FOR THE PROUDLY ECONOMICAL</div><h1>Less bill.<br><em>More brag.</em></h1><p>You bring the ideas. Free models bring the tokens.<br>We bring a wildly unnecessary leaderboard.</p><div class="hero-actions"><button class="button primary" data-action="join">${joined?'You’re in the club':'Claim your cheapo status'} ${arrow}</button><span class="micro-note">Free to join.<br>Obviously.</span></div></div><button class="champion-card" data-profile="${p.id}" aria-label="View ${esc(p.name)}’s profile"><span class="eyebrow">ALL-TIME FREE API CHAMPION</span><h2>Top Cheapo</h2><div class="trophy-stage"><span class="orbit orbit-one">✦</span>${trophy}<span class="orbit orbit-two">✧</span><span class="trophy-caption">BIG BRAIN<br>SMALL BILL</span></div><div class="champion-person">${avatar(p)}<div><strong>${p.name}</strong><span>@${p.handle}</span></div><span class="champion-link">↗</span></div><div class="champion-score"><strong>${format(p.free)}</strong><span>free API tokens<br>and counting*</span></div><span class="card-fine">*Sample data. Real champion energy.</span></button></section>`;
  } else {
    document.getElementById('hero').innerHTML=`<section class="hero arcade-hero"><div class="arcade-hero-top"><div><div class="eyebrow"><span class="live-dot"></span> FREE TOKENS. FULL BRAGGING RIGHTS.</div><h1>HIGH SCORES.<br><span>LOW BILLS.</span></h1></div><div class="arcade-intro"><span class="pixel-spark" aria-hidden="true">✦</span><p>Welcome to the game where<br>the big spenders don’t win.</p><button class="button primary" data-action="join">${joined?'View your player card':'Enter the leaderboard'} ${arrow}</button></div></div><div class="podium-label eyebrow">ALL-TIME FREE API CHAMPIONS</div><div class="podium" aria-label="All-time free API champions">${[leaders[1],leaders[0],leaders[2]].map((p,i)=>`<button class="podium-player place-${[2,1,3][i]}" data-profile="${p.id}"><span class="podium-rank">${i===1?'★ TOP CHEAPO':'0'+[2,1,3][i]+' / '+(i===0?'PENNY PINCHER':'BUDGET ROYALTY')}</span><div class="podium-identity">${avatar(p)}<div><strong>${p.name}</strong><span>@${p.handle}</span></div>${i===1?'<span class="pixel-crown" aria-hidden="true">♛</span>':''}</div><div class="podium-score">${format(p.free)}<span>FREE API TOKENS</span></div><span class="podium-bar"></span></button>`).join('')}</div></section>`;
  }
}
function renderStats() { document.getElementById('community-stats').innerHTML=`<section class="community-stats" aria-label="Sample community totals"><div><span class="stat-icon">${arcade?'↗':'✳'}</span><div><strong>${format(sum('free'))}</strong><span>free API tokens, together</span></div></div><div><span class="stat-icon">${arcade?'◈':'☺'}</span><div><strong>${allPeople().length}</strong><span>proud cheapos on the board</span></div></div><div><span class="stat-icon">${arcade?'◎':'↳'}</span><div><strong>100% opt-in</strong><span>your stats, your choice</span></div></div><span class="sample-stamp">SAMPLE COMMUNITY</span></section>`; }
function renderBoard() {
  const list=ranked(); const query=state.query.trim().toLowerCase(); const visible=list.filter(p=>(p.name+' '+p.handle).toLowerCase().includes(query));
  document.getElementById('ranking').innerHTML=`<div class="table-scroll"><table><thead><tr><th class="rank-cell" scope="col">Rank</th><th scope="col">${arcade?'Player':'Fellow cheapo'}</th><th class="total-cell" scope="col">${state.category==='free'?'Free API':'Local'} tokens</th><th class="trend-cell" scope="col">${state.period==='month'?'Share':'This month'}</th></tr></thead><tbody>${visible.map(p=>{const n=list.findIndex(x=>x.id===p.id)+1;return `<tr class="${p.id==='you'?'your-row':''}"><td class="rank-cell"><span class="rank-number ${n<=3?'rank-top rank-'+n:''}">${String(n).padStart(2,'0')}</span></td><td><button class="person-button" data-profile="${p.id}">${avatar(p)}<span><strong>${esc(p.name)} ${p.id==='you'?'<span class="you-tag">YOU</span>':''}</strong><small>@${esc(p.handle)}</small></span></button></td><td class="total-cell"><strong>${format(p[field()])}</strong>${n===1?'<span class="leader-tag">'+(state.category==='free'?'TOP CHEAPO':'LOCAL LEGEND')+'</span>':''}</td><td class="trend-cell">${state.period==='month'?(100*p[field()]/sum(field())).toFixed(1)+'%':'+'+format(p[state.category==='free'?'month':'localMonth'])}</td></tr>`;}).join('')}</tbody></table>${visible.length?'':`<div class="empty-state"><span>⌕</span><h3>No cheapos found.</h3><p>Try another name or handle.</p><button class="text-button" data-action="clear-search">Clear search</button></div>`}</div><div class="table-bottom"><span>${visible.length} of ${allPeople().length} participants</span><span>${state.period==='month'?'September 2026 · demo month':'All-time reported usage'} <span class="small-dot"></span></span></div>`;
  document.getElementById('board-note').innerHTML=state.category==='free'?'Self-reported tokens on public-free API routes. Paid, included-plan, local, and unknown usage are excluded. <button class="inline-link" data-action="how">What counts? ↗</button>':'Local-model tokens are shown separately. $0 API spend does not mean $0 hardware or electricity cost. <button class="inline-link" data-action="how">What counts? ↗</button>';
  document.querySelectorAll('[data-period]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.period===state.period)));
  document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===state.category)));
}
function renderSide() {
  document.getElementById('side-panel').innerHTML=`<section class="join-card"><div class="eyebrow">${joined?'MEMBERSHIP: EXTREMELY CHEAP':arcade?'PLAYER SLOT AVAILABLE':'YOUR NAME COULD BE HERE'}</div><div class="join-art" aria-hidden="true">${joined?'✓':arcade?'[ + ]':'✳'}</div><h2>${joined?'Welcome to the cheap seats.':arcade?'Got game?<br>Get on the board.':'A little flex.<br>For a little bill.'}</h2><p>${joined?'Your demo profile is public in this browser only. You’re in control of what you share.':'Connect your X account and choose to share your usage from cheapoS. No prompts. No code. Just the numbers.'}</p><button class="button ${arcade?'primary':''}" data-action="join">${joined?'Manage participation':arcade?'Create your player card':'Join the club'} ${arrow}</button><span class="join-fine">${joined?'Demo mode · no real uploads':'Opt in once. Leave whenever.'}</span></section><section class="small-note"><span aria-hidden="true">${arcade?'ⓘ':'↳'}</span><div><h3>Brag responsibly.</h3><p>This is a usage board, not a measure of code quality. Build good stuff. Don’t burn tokens for a badge.</p></div></section>`;
}
function showModal(content,kind='') { modal.className=kind; modal.innerHTML=`<button class="modal-close" data-action="close" aria-label="Close dialog">×</button>${content}`; if(!modal.open)modal.showModal(); const heading=modal.querySelector('h2');heading.tabIndex=-1;heading.focus({preventScroll:true}); }
function joinFlow() {
  if(joined) { showModal(`<div class="eyebrow">YOUR DEMO MEMBERSHIP</div><h2 id="modal-title">You’re officially<br>a cheapo.</h2><div class="connected-person">${avatar(demoPerson)}<div><strong>${demoPerson.name}</strong><span>@${demoPerson.handle}</span></div><span class="connection-tag">Demo</span></div><div class="privacy-preview"><div><span>Shared free API tokens</span><strong>${format(demoPerson.free)}</strong></div><div><span>Shared local tokens · separate board</span><strong>${format(demoPerson.local)}</strong></div><div><span>Uploads</span><strong>None · this is a demo</strong></div></div><p>In the real app, stopping sharing would disconnect uploads and remove your public entry. Your private cheapoS history would stay yours.</p><button class="button primary full" data-action="copy-brag">Copy a demo brag ↗</button><button class="button subtle full" data-action="leave">Stop sharing & remove demo profile</button><p class="modal-fine">Only this browser’s demo preference is stored. No account was connected.</p>`);return; }
  showModal(`<div class="eyebrow">${arcade?'INSERT ZERO COINS':'WELCOME TO THE CLUB'}</div><h2 id="modal-title">Put your cheap<br>on the map.</h2><p>Your X profile is your public identity. Your cheapoS usage is your score. You choose whether to share.</p><ol class="join-steps"><li><span>01</span><div><strong>Connect your X account</strong><p>One identity. One place on the board.</p></div></li><li><span>02</span><div><strong>Preview your numbers</strong><p>See exactly what will be public.</p></div></li><li><span>03</span><div><strong>Opt in from cheapoS</strong><p>Turn sharing off whenever you like.</p></div></li></ol><div class="demo-notice"><strong>Interactive demo</strong><span>The next step uses a fictional X account. No sign-in, uploads, or posts happen.</span></div><button class="button primary full" data-action="demo-connect"><span class="x-mark">𝕏</span> Try demo X connection ${arrow}</button><p class="modal-fine">Production sign-in would request identity access, never permission to post.</p>`);
}
function previewConsent() {
  showModal(`<div class="eyebrow">STEP 2 / MAKE IT YOUR CALL</div><h2 id="modal-title">Your public<br>brag sheet.</h2><div class="connected-person">${avatar(demoPerson)}<div><strong>${demoPerson.name}</strong><span>@${demoPerson.handle}</span></div><span class="connection-tag">Demo X</span></div><div class="privacy-preview"><div><span>All-time free API tokens</span><strong>${format(demoPerson.free)}</strong></div><div><span>This month · free API tokens</span><strong>${format(demoPerson.month)}</strong></div><div><span>Local tokens · separate board</span><strong>${format(demoPerson.local)}</strong></div></div><p class="privacy-copy"><strong>Public:</strong> your name, handle, avatar, token totals, and rank.<br><strong>Never shared:</strong> prompts, code, repository names, keys, or chat history.</p><label class="consent"><input type="checkbox" id="consent"><span>I choose to publish these demo stats and this fictional profile on the leaderboard. I can remove them at any time.</span></label><button class="button primary full" data-action="opt-in" disabled>Count me in ${arrow}</button><p class="modal-fine">This preview includes lifetime totals. A real opt-in would show your actual numbers before any upload.</p>`);
}
function how() { showModal(`<div class="eyebrow">THE RULES ARE PRETTY CHEAP</div><h2 id="modal-title">Big numbers.<br>Honest labels.</h2><div class="explanation-block"><h3>What earns a place?</h3><p>Reported input + output tokens used on public-free API routes through cheapoS. Your profile is tied to an X identity, and you explicitly opt in before sharing.</p></div><div class="explanation-block"><h3>What stays separate?</h3><p>Local-model tokens have their own board. Paid, subscription-included, estimated, and unknown-billing usage don’t count toward the public-free crown. Missing usage isn’t a zero.</p></div><div class="explanation-block"><h3>Does “Top Cheapo” mean best coder?</h3><p>Nope. It’s a playful usage title, not a quality score or proof of money saved. X sign-in confirms identity, not the truth of self-reported usage.</p></div><div class="demo-notice"><strong>Everything here is sample data</strong><span>All-time and September figures, people, and rankings are fictional. Connecting X and opting in are simulated locally.</span></div><button class="button primary full" data-action="join">${joined?'Your membership':'Sounds like my kind of club'} ${arrow}</button>`); }
function privacy() { showModal(`<div class="eyebrow">PRIVACY, WITHOUT THE FINE-PRINT GYMNASTICS</div><h2 id="modal-title">Your data.<br>Your call.</h2><div class="explanation-block"><h3>In this prototype</h3><p>No network requests, telemetry, or real X connection. Only an on/off demo preference is saved in this browser. Sample stats and profiles are fictional.</p></div><div class="explanation-block"><h3>In the proposed product</h3><p>Sharing starts off. cheapoS shows a preview, you connect X, then explicitly enable uploads. Only identity and usage aggregates are public. You can stop uploads and request removal of the public entry. No prompts, project files, or credentials are uploaded.</p></div><button class="button primary full" data-action="${joined?'leave':'close'}">${joined?'Remove my demo profile':'Got it'}</button>`); }
function profile(id) {
  const p=allPeople().find(p=>p.id===id); if(!p)return; const position=ranked().findIndex(x=>x.id===id)+1;
  showModal(`<div class="eyebrow">${id==='you'?'YOUR PLAYER CARD':'FICTIONAL COMMUNITY PROFILE'}</div><div class="profile-heading">${avatar(p)}<span class="profile-rank">#${position}</span></div><h2 id="modal-title">${esc(p.name)}</h2><span class="profile-handle">@${esc(p.handle)}</span><p>${esc(p.bio)}</p><span class="profile-title">${p.title}</span><div class="profile-stats"><div><strong>${format(p.free)}</strong><span>all-time free API tokens</span></div><div><strong>${format(p.month)}</strong><span>free API tokens this month</span></div><div><strong>${format(p.local)}</strong><span>local tokens · separate</span></div></div><p class="modal-fine">Rank #${position} on the ${state.period==='month'?'September':'all-time'} ${state.category==='free'?'free API':'local'} board. Self-reported sample usage; no verified-savings claim.</p><button class="button primary full" data-action="${id==='you'?'join':'close'}">${id==='you'?'Manage participation':'Nice. Very cheap.'}</button>`);
}
document.addEventListener('click',async e=>{
  const target=e.target.closest('button,a'); if(!target)return;
  if(target.dataset.profile){profile(target.dataset.profile);return;}
  if(target.dataset.period){state.period=target.dataset.period;renderBoard();return;}
  if(target.dataset.category){state.category=target.dataset.category;renderBoard();return;}
  const action=target.dataset.action; if(!action)return;
  if(action==='join')joinFlow();
  if(action==='how')how();
  if(action==='privacy')privacy();
  if(action==='close')modal.close();
  if(action==='demo-connect')previewConsent();
  if(action==='opt-in'&&document.getElementById('consent')?.checked){setJoined(true);modal.close();shell();notify('You’re in! Your demo profile is on the board. Nothing was uploaded.');}
  if(action==='leave'){setJoined(false);modal.close();shell();notify('Demo profile removed. Your cheapoS data stays yours.');}
  if(action==='clear-search'){state.query='';document.getElementById('search').value='';renderBoard();document.getElementById('search').focus();}
  if(action==='copy-brag'){
    const text='Demo brag: 41.6M free API tokens with cheapoS. Big token energy. Small bill behavior. #TopCheapo';
    try{await navigator.clipboard.writeText(text);notify('Demo brag copied. Nothing posted.');}catch(_){notify('Clipboard unavailable. Your brag: 41.6M free API tokens with cheapoS!');}
  }
});
document.addEventListener('change',e=>{if(e.target.id==='consent')modal.querySelector('[data-action="opt-in"]').disabled=!e.target.checked;});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
shell();
