import Link from "next/link";
import {leaderboard} from "@/lib/leaderboard";
export const dynamic="force-dynamic";
export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const query=await searchParams;
 const category=query.category==="local"?"local":"public_free";
 const period=query.period==="month"?"month":"all";
 const board=await leaderboard(category,period);
 return <><section className="hero"><div><p className="eyebrow">BIG IDEAS. SMALL BILLS.</p><h1>Good work.<br/><em>Cheap thrills.</em></h1><p className="lede">A little ingenuity goes a long way. Meet the builders making more with less, one cheapoS task at a time.</p><Link className="button" href="/community">Meet the club ↗</Link></div><aside className="hero-card"><span className="sun" aria-hidden="true">✳</span><p className="eyebrow">THE TOP CHEAPO</p><h2>A little friendly<br/>competition.</h2><p>Real members. App-synced usage.<br/>Plenty of room for your next idea.</p><Link href="/about">What counts toward the board →</Link></aside></section>
 <section className="board" aria-labelledby="board-title"><div className="section-heading"><div><p className="eyebrow">THE RESOURCEFUL ONES</p><h2 id="board-title">Small spend. Big energy.</h2></div><span className="pill">App-synced · client-reported</span></div>
 <form className="filters"><label>Board<select name="category" defaultValue={category}><option value="public_free">Public-free API tokens</option><option value="local">Local-model tokens</option></select></label><label>Period<select name="period" defaultValue={period}><option value="all">Since joining</option><option value="month">This month · UTC</option></select></label><button className="button secondary" type="submit">Show rankings</button></form>
 {board.entries.length ? <div className="table-wrap"><table><caption className="sr-only">Rankings by reported token usage</caption><thead><tr><th>Rank</th><th>Builder</th><th>Tokens</th></tr></thead><tbody>{board.entries.map((person,i)=><tr key={person.handle}><td>{i+1}</td><td><strong>{person.display_name}</strong><small>@{person.handle}</small></td><td>{person.tokens.toLocaleString("en-US")}</td></tr>)}</tbody></table></div> : <div className="empty" role="status"><span aria-hidden="true">↗</span><h3>{board.state==="unavailable"?"The scoreboard is taking a breather.":board.state==="setup"?"The club is getting ready.":"The first spot could be yours."}</h3><p>{board.state==="unavailable"?"We can’t reach the rankings right now. Your local cheapoS work is unaffected. Try again shortly.":board.state==="setup"?"Live rankings aren’t connected yet. There are no pretend scores here—just room for our first builders.":"No shared usage in this category and period yet."}</p></div>}
 <p className="fine">Usage is shared by opted-in installations, not independently verified. Imported history and estimates do not count toward these rankings.</p></section>
 <section className="invite"><div><p className="eyebrow">MORE THAN A NUMBER</p><h2>What are you making?</h2><p>Swap ideas, share a win, or find your next wonderfully unnecessary project.</p></div><Link className="button" href="/community">Explore the community →</Link></section></>;
}
